class EmissionParameters:
    lower: list[float]
    upper: list[float]
    profile: list[int]
    Suzuki_k: list[float]

    def __init__(self): ...

    def len(self) -> int: ...

    def validate(self) -> int: ...

    def from_values(self, lower: float, upper: float, profile: int, Suzuki_k: float) -> None: ...

    def from_lists(self, lower: float, upper: float, profile: int, Suzuki_k: float) -> None: ...

    def clear(self) -> None: ...

    def add_profile(self, lower: float, upper: float, profile: int, Suzuki_k: float) -> None: ...

    def remove_profile(self, profile_i: int) -> None: ...

    def describe(self) -> None: ...

def Suzuki_k_from_peak(Suzuki_peak: float, lower: float, upper: float) -> float: ...

def Suzuki_peak_from_k(Suzuki_k: float, lower: float, upper: float) -> float: ...
    
def _emission_dict(p: EmissionParameters) -> dict[str, float]: ...

def _emission_params_equal(p1: EmissionParameters, p2: EmissionParameters) -> bool: ...