import numpy as np

class GrainParameters:
    bins: int
    diameter: list[np.float64]
    density: list[np.float64]
    proportion: list[np.float64]

    def __init__(self): ...

    def len(self) -> int: ...

    def from_values(self, diameter: float, density: float, proportion: float): ...

    def from_lists(self, diameters: float, densities: float, proportions: float): ...

    def clear(self) -> None: ...

    def add_grain(self, diameter: float, density: float, proportion: float) -> None: ...

    def remove_grain(self, grain_i: int) -> None: ...

    def validate(self) -> int: ...

    def describe(self) -> None: ...